In [1]:
import os
import pandas as pd
import csv

In [2]:
income_data='kaggle_income.csv'
income_pd = pd.read_csv(income_data)
brewery_data='breweries_us.csv'
brewery_pd = pd.read_csv(brewery_data)

In [5]:
income_pd

,id,State_Code,State_Name,State_ab,County,City,Place,Type,Primary,Zip_Code,Area_Code,ALand,AWater,Lat,Lon,Mean,Median,Stdev,sum_w
0,1011000,1,Alabama,AL,Mobile County,Chickasaw,Chickasaw city,City,place,36611,251,10894952,909156,30.771450,-88.079697,38773,30506,33101,1638.260513
1,1011010,1,Alabama,AL,Barbour County,Louisville,Clio city,City,place,36048,334,26070325,23254,31.708516,-85.611039,37725,19528,43789,258.017685
2,1011020,1,Alabama,AL,Shelby County,Columbiana,Columbiana city,City,place,35051,205,44835274,261034,33.191452,-86.615618,54606,31930,57348,926.031000
3,1011030,1,Alabama,AL,Mobile County,Satsuma,Creola city,City,place,36572,251,36878729,2374530,30.874343,-88.009442,63919,52814,47707,378.114619
4,1011040,1,Alabama,AL,Mobile County,Dauphin Island,Dauphin Island,Town,place,36528,251,16204185,413605152,30.250913,-88.171268,77948,67225,54270,282.320328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32521,720296,72,Puerto Rico,PR,Adjuntas Municipio,Guaynabo,Adjuntas,Track,Track,970,787,589417,1691,18.397925,-66.130633,30649,13729,37977,1321.278082
32522,7202966,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,602,787,1801613,795887,18.385424,-67.203310,15520,9923,15541,238.813450
32523,7202976,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,602,787,11031227,0,18.356565,-67.180686,41933,34054,31539,313.551070
32524,7202986,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,602,787,0,33597561,18.412041,-67.213413,0,0,0,0.000000
32525,7202996,72,Puerto Rico,PR,Adjuntas Municipio,Aguadilla,Adjuntas,Track,Track,603,787,6476604,2717115,18.478094,-67.160453,28049,20229,33333,512.884803

In [6]:
brewery_pd

,brewery_name,type,address,website,state,state_breweries
0,Valley Brewing Co.,Brewpub,"PO Box 4653, Stockton, California, 95204",http://www.valleybrew.com/,CALIFORNIA,284
1,Valley Brewing Co.,Brewpub,"157 Adams St., Stockton, California, 95204",http://www.valleybrew.com/,CALIFORNIA,284
2,Valley Brewing Co,Microbrewery,"1950 W Freemont, Stockton, California, 95203",http://www.valleybrew.com/,CALIFORNIA,284
3,Ukiah Brewing Company,Brewpub,"102 S. State St., Ukiah, California, 95482",http://www.ukiahbrewingco.com/,CALIFORNIA,284
4,Tustin Brewing Co.,Brewpub,"13011 Newport Ave. #100, Tustin, California, 9...",http://www.tustinbrewery.com/,CALIFORNIA,284
...,...,...,...,...,...,...
2402,Capitol City Brewing Company (Capitol Hill),Brewpub,"2 Massachusetts Ave., Washington, DC, Washingt...",http://www.capcitybrew.com/,WASHINGTON-DC,9
2403,Capitol City Brewing Company,Brewpub,"1100 New York Ave. NW, Washington, DC, Washing...",http://www.capcitybrew.com/,WASHINGTON-DC,9
2404,Old Harbor Brewery,Brewpub,"Gen del Valle 1021 Urb Delicias, San Juan, PR,...",http://oldharborbrewery.com/,PUERTO-RICO,3
2405,Isla Verde Brewing Co.,Microbrewery,"Condiminum Torrimar Plaza # 14B, Guaynabo , PR...",...,PUERTO-RICO,3
2406,Cerveceria India Inc,RegionalBrewery,"PO Box 1690, Mayaguez, PR, 681",...,PUERTO-RICO,3

In [3]:
brewery_pd['state'] = brewery_pd['state'].str.upper()
breweries_by_state = brewery_pd.groupby(['state'])
brewery_state_count = breweries_by_state.count()
brewery_state_count = brewery_state_count['state_breweries']
brewery_state_count

state
ALABAMA             6
ALASKA             14
ARIZONA            34
ARKANSAS            7
CALIFORNIA        284
COLORADO          182
CONNECTICUT        11
DELAWARE           14
FLORIDA            99
GEORGIA            47
HAWAII             10
IDAHO              28
ILLINOIS           74
INDIANA            31
IOWA               13
KANSAS             26
KENTUCKY           12
LOUISIANA          15
MAINE              44
MARYLAND           43
MASSACHUSETTS      71
MICHIGAN           94
MINNESOTA          40
MISSOURI           21
MONTANA            32
NEBRASKA           15
NEVADA             18
NEW-HAMPSHIRE      18
NEW-JERSEY         41
NEW-MEXICO         37
NEW-YORK          107
NORTH-CAROLINA     61
NORTH-DAKOTA        5
OHIO               56
OKLAHOMA           16
OREGON            156
PENNSYLVANIA      107
PUERTO-RICO         3
RHODE-ISLAND       12
SOUTH-CAROLINA     32
SOUTH-DAKOTA       11
TENNESSEE          28
TEXAS              90
UTAH               21
VERMONT            28
VIRGINIA           43
WASHINGTON        151
WASHINGTON-DC       9
WEST-VIRGINIA       5
WISCONSIN          77
WYOMING             8
Name: state_breweries, dtype: int64

In [35]:
Chicago = brewery_pd[brewery_pd['address'].str.contains('Chicago, Illinois')]

In [36]:
Chicago

,brewery_name,type,address,website,state,state_breweries
812,Todds Beer Inc.,ContractBrewery,"3216 N Sheffield, Fl 2, Chicago, Illinois, 60657",http://www.toddsbeer.com/,ILLINOIS,74
819,Slopeside Brewing Co.,ContractBrewery,"3445 N. Elaine Pl., Chicago, Illinois, 60657",...,ILLINOIS,74
820,Rock Bottom Brewery (#7),Brewpub,"1 W. Grand Ave., Chicago, Illinois, 60610",http://www.rockbottom.com/,ILLINOIS,74
824,RJ's Ginseng,ContractBrewery,"P.O. Box 10437, Chicago, Illinois, 60610",...,ILLINOIS,74
825,River West Brewing Co.,Brewpub-Closed,"925 W. Chicago Ave., Chicago, Illinois, 60622",...,ILLINOIS,74
826,Revolution Brewing,Microbrewery,"P O Box 471534, Chicago, Illinois, 60647",http://revbrew.com/,ILLINOIS,74
830,Piece Brewery,Brewpub,"1927 W North Ave., Chicago, Illinois, 60622",http://www.piecechicago.com/,ILLINOIS,74
831,Peter Hand Brewing Co.,Microbrewery,"Chicago, Illinois",...,ILLINOIS,74
841,Metropolitan Brewing Co.,Microbrewery,"Chicago, Illinois",http://www.metropolitanbrewing.com/,ILLINOIS,74
842,Metropolitan Brewing Co,Microbrewery,"5121 N Ravenswood Ave, Chicago, Illinois, 60640",www.metropolitanbrewing.com,ILLINOIS,74
853,Half Acre Beer Co,Microbrewery,"4257 N. Lincoln Ave., Chicago, Illinois, 60618",http://www.halfacrebeer.com/,ILLINOIS,74
857,Goose Island Brewing Co. (#3),Brewpub,"3535 N Clark St, Chicago, Illinois, 60657",http://www.gooseisland.com/,ILLINOIS,74
858,Goose Island Brewing Co. (#2),Microbrewery,"1800 W. Fulton, Chicago, Illinois, 60612",http://www.gooseisland.com/,ILLINOIS,74
859,Goose Island Brewing Co. (#1),Brewpub,"1800 N. Clybourn, Chicago, Illinois, 60614",http://www.gooseisland.com/,ILLINOIS,74
860,Golden Prairie Brewing Co.,Microbrewery,"2536 N. Elston Ave., Chicago, Illinois, 60647",...,ILLINOIS,74
871,"Drinking and Writing Brewery, The",Microbrewery,"1444 W Hollywood Ave, Chicago, Illinois, 60660",http://www.drinkingandwriting.com/,ILLINOIS,74
874,Chicago Brewing Company,Microbrewery,"1830 N. Besly Ct., Chicago, Illinois, 60622",http://www.chicagobrewingcolv.com/,ILLINOIS,74
882,"Beverly Brewing Company, LLC",ContractBrewery,"10448 South Seeley Ave, Chicago, Illinois, 60643",http://www.beverlybrewingco.com/,ILLINOIS,74